const names = {
  "Alfie-James": true,
  "Artoo Dogtoo": true,
  "Baby Boomer": true,
  "Beau Dacious": true,
  "Bruce Wayne": true,
  "Buzz Pawldrin": true,
  "Casper the Friendly Dog": true,
  "Chew Barka": true,
  "Cornelius Fudge": true,
  "Crabcake Benedictt": true,
  "E.T.": true,
  "Ernest Hemingway": true,
  "Ginger Noodle": true,
  "Hairy Paw-ter": true,
  "Harley Quinn": true,
  "Harry Potter": true,
  "Jimmy Chew": true,
  "Kal-El": true,
  "Koby Teeth": true,
  "Luke Skywalker": true,
  "Luna Lovegood": true,
  "Mister Awesome of Wales": true,
  "Mister Cliquishwumps": true,
  "Mister Clubby": true,
  "Mister Densewumps": true,
  "Mister Dullwumps": true,
  "Mister Frisky": true,
  "Mister Hotlickle": true,
  "Mister Snobby": true,
  "Mr. Clannishtoes": true,
  "Mr. Dim": true,
  "Mr. Dumbpants": true,
  "Mr. Ethnicpants": true,
  "Mr. Mischievouspop": true,
  "Mr. Mistoffelees": true,
  "Mr. Privatewumps": true,
  "Mr. Spiffing": true,
  "Muttley Crue": true,
  "Neville Longbottom": true,
  "Ozzy Pawsborne": true,
  "Pecan Sandy": true,
  "Pepper Potts": true,
  "Pom pom": true,
  "Princess Leia": true,
  "Reeses Puppycups": true,
  "Salvador Dogi": true,
  "Sherlock Bones": true,
  "Sir Stinks Alot": true,
  "Sonic Shoelace": true,
  "Spark Pug": true,
  "Tater Tot": true,
  "Vienna Sausage": true,
  "William ShakesPaw": true,
  "Willie Nelson": true,
  "Winne the Poodle": true,
  "Winston Fur-chill": true,
  "Won Ton": true,
  "Wonder Woman": true,
  "Yin-Yang": true,
  Abby: true,
  Ace: true,
  Aleksandar: true,
  Alexander: true,
  Allie: true,
  Ambassador: true,
  Amber: true,
  Angel: true,
  Anjolaoluwa: true,
  Annie: true,
  Apollo: true,
  Apricot: true,
  Archibald: true,
  Aristocrat: true,
  Aristotle: true,
  Arya: true,
  Aslan: true,
  Athena: true,
  Auburn: true,
  Augustine: true,
  Autumn: true,
  Ava: true,
  Baby: true,
  Bacon: true,
  Badger: true,
  Baggage: true,
  Baguette: true,
  Bailey: true,
  Bandit: true,
  Banjo: true,
  Barcode: true,
  Barkley: true,
  Barkness: true,
  Barney: true,
  Baxter: true,
  Beanie: true,
  Beans: true,
  Bear: true,
  Beau: true,
  Beer: true,
  Bella: true,
  Bellatrix: true,
  Belle: true,
  Benji: true,
  Benny: true,
  Bentley: true,
  Bikus: true,
  Bilbo: true,
  Billy: true,
  Binky: true,
  Blade: true,
  Blue: true,
  Bo: true,
  Bob: true,
  Bobcat: true,
  Bogo: true,
  Bonko: true,
  Bonnie: true,
  Boomer: true,
  Bozo: true,
  Brady: true,
  Brewski: true,
  Brody: true,
  Broseph: true,
  Bruce: true,
  Bruno: true,
  Brutus: true,
  Bubble: true,
  Buddy: true,
  Burger: true,
  Buster: true,
  Butterbean: true,
  Butterscotch: true,
  Buzz: true,
  Cacao: true,
  Cali: true,
  Callie: true,
  Cash: true,
  Catfish: true,
  Catnip: true,
  Cedric: true,
  Chance: true,
  Chandler: true,
  Charlie: true,
  Charlotte: true,
  Chase: true,
  Checkers: true,
  Cheddar: true,
  Cheese: true,
  Chernobyl: true,
  Chess: true,
  Chester: true,
  Chewbacca: true,
  Chewy: true,
  Chico: true,
  Chip: true,
  Chippy: true,
  Chloe: true,
  Chowbella: true,
  Chronic: true,
  Chubs: true,
  Chunk: true,
  Cleo: true,
  Cloud: true,
  Coco: true,
  Cody: true,
  Cookie: true,
  Cooper: true,
  Copper: true,
  Daisy: true,
  Dakota: true,
  Dalmatian: true,
  Decopatch: true,
  Delilah: true,
  Dexter: true,
  Dice: true,
  Dickens: true,
  Diesel: true,
  Dink: true,
  Dinky: true,
  Dixie: true,
  Dobut: true,
  Domino: true,
  Dot: true,
  DotCom: true,
  Duke: true,
  Eggroll: true,
  Einstein: true,
  Ella: true,
  Ellie: true,
  Elmo: true,
  Emma: true,
  Enchilada: true,
  Espresso: true,
  Fabio: true,
  Felix: true,
  Figaro: true,
  Finn: true,
  Fiona: true,
  Frankie: true,
  Fred: true,
  George: true,
  Georgia: true,
  Gigi: true,
  Ginger: true,
  Gizmo: true,
  Gonzo: true,
  Google: true,
  Gracie: true,
  Gryffindor: true,
  Guinness: true,
  Gunner: true,
  Gus: true,
  Hank: true,
  Harley: true,
  Harper: true,
  Hashtag: true,
  Hazel: true,
  Heathcliff: true,
  Heidi: true,
  Henry: true,
  Hermione: true,
  Hobbit: true,
  Holly: true,
  Honey: true,
  Hotdog: true,
  Hunter: true,
  Itsy: true,
  Ivy: true,
  Izzy: true,
  Jack: true,
  Jackson: true,
  Jake: true,
  Jalapeno: true,
  Janeway: true,
  Jasmine: true,
  Jasper: true,
  Jax: true,
  Jellybean: true,
  Jess: true,
  Joey: true,
  Joppy: true,
  Josie: true,
  Keeko: true,
  King: true,
  Kobe: true,
  Koda: true,
  Kona: true,
  Krypto: true,
  Lacey: true,
  Lady: true,
  Larry: true,
  Latke: true,
  Latte: true,
  Layla: true,
  Leia: true,
  Lemon: true,
  Leo: true,
  Lexi: true,
  Lilly: true,
  Lily: true,
  Loco: true,
  Loki: true,
  Lola: true,
  Lorenzo: true,
  Louie: true,
  Lucky: true,
  Lucy: true,
  Luke: true,
  Lulu: true,
  Lulz: true,
  Luna: true,
  Lupin: true,
  Mac: true,
  Macaroni: true,
  Macavity: true,
  Macy: true,
  Madame: true,
  Maddie: true,
  Maggie: true,
  Maher: true,
  Malfoy: true,
  Mark: true,
  Marley: true,
  Marmalade: true,
  Marshmallow: true,
  Mason: true,
  Mateo: true,
  Maverick: true,
  Max: true,
  Maya: true,
  McDoggins: true,
  McElfinpants: true,
  McFriendly: true,
  McGregariouspants: true,
  McMellow: true,
  McPlayful: true,
  McSnobbish: true,
  McSocial: true,
  McStupid: true,
  Mia: true,
  Micha: true,
  Mickey: true,
  Mihir: true,
  Mike: true,
  Mila: true,
  Millie: true,
  Milo: true,
  Minerva: true,
  Minnie: true,
  Mippy: true,
  Mittens: true,
  Mocha: true,
  Molly: true,
  Moose: true,
  Mope: true,
  Mungojerrie: true,
  Murphy: true,
  Musab: true,
  Nacho: true,
  Nala: true,
  Nibit: true,
  Nina: true,
  Nova: true,
  Odin: true,
  Olive: true,
  Oliver: true,
  Ollie: true,
  Orca: true,
  Oreo: true,
  Oscar: true,
  Otis: true,
  Paisley: true,
  Pancake: true,
  Panda: true,
  Patch: true,
  Patchwork: true,
  Peanut: true,
  Pearl: true,
  Pebble: true,
  Peeve: true,
  Penelope: true,
  Penguin: true,
  Penny: true,
  Pepper: true,
  Phoebe: true,
  Phoenix: true,
  Piano: true,
  Pickle: true,
  Pinot: true,
  Piper: true,
  Poggo: true,
  PoopDolla: true,
  Poopoo: true,
  Pope: true,
  Porkchop: true,
  Pretzel: true,
  Prince: true,
  Princess: true,
  Puffin: true,
  Puffins: true,
  Queso: true,
  Raisin: true,
  Ranger: true,
  Rex: true,
  Rhubarb: true,
  Riddick: true,
  Riley: true,
  Rocco: true,
  Rocky: true,
  Romeo: true,
  Roscoe: true,
  Rosie: true,
  Roxie: true,
  Roxy: true,
  Ruby: true,
  Rudy: true,
  Rusty: true,
  Sadie: true,
  Sam: true,
  Sammy: true,
  Samson: true,
  Sandwich: true,
  Sandy: true,
  Sasha: true,
  Sativa: true,
  Scibbly: true,
  Scout: true,
  Shadow: true,
  Shelby: true,
  Simba: true,
  Sirius: true,
  Sitka: true,
  Slinkerton: true,
  Sloppy: true,
  Snoopy: true,
  Socks: true,
  Socksy: true,
  Sophie: true,
  Splatter: true,
  Sponge: true,
  Spot: true,
  Stan: true,
  Stella: true,
  Stevie: true,
  Stewie: true,
  Stinkerbell: true,
  Stinky: true,
  Suduko: true,
  Sugar: true,
  Sundae: true,
  Swiffer: true,
  Sydney: true,
  Sylvester: true,
  Taco: true,
  Tangerine: true,
  Tank: true,
  Teddy: true,
  Thor: true,
  Tibs: true,
  Tiger: true,
  Toby: true,
  Tonks: true,
  Trim: true,
  Trixie: true,
  Tucker: true,
  Tuxedo: true,
  Twinky: true,
  Tyrion: true,
  Tyson: true,
  Ukulele: true,
  Waldo: true,
  Walter: true,
  Weasley: true,
  WiFi: true,
  Willow: true,
  Winnie: true,
  Winston: true,
  Woofgang: true,
  Xena: true,
  Yeti: true,
  Yolo: true,
  Yoyo: true,
  zAmberz: true,
  Zebra: true,
  Zeke: true,
  Zelda: true,
  Zeus: true,
  Ziggy: true,
  Zoe: true,
  Zoey: true,
};

export default Object.keys(names);
